### PR TITLE
refactor: update axios version and handle breaking changes

### LINKED ISSUE #54: Support axios v1.x.x
Using with a v1+ of axios is not compatible with `ts-retrofit`. Couple of changes that I noticed affects `ts-retrofit`:

* `AxiosRequestConfig` - `InternalAxiosRequestConfig`
* `AxiosTransformer` - `AxiosRequestTransformer` and `AxiosResponseTransformer`

### PR DESCRIPTION
**Pull request by msmur**
Hello,

I'm raising this PR to update the axios dependency to the latest version.
Versions prior to 1.6 have an associated security vulnerability, which make it difficult to justify ts-retrofit usage in production environments.

This will also resolve #54.

Changes include:
- Changing the types of `AxiosRequestConfig` to `InternalAxiosRequestConfig`
- Changing the use of `AxiosTransformer` to `AxiosRequestTransformer` and `AxiosResponseTransformer`
- Updating existing tests to ascertain that they still pass without issue.

I'm not aware of all the project internals, and made the minimum changes to satisfy the axios upgrade. Please do let me know if any other changes are required!

### CODE REVIEW

**Comment by devcsrj** [comment]
Hi @nullcc! Does this PR look good enough for merge?

**Comment by eriknyk** [comment]
+1 here, is this library still maintained?

**Comment by devcsrj** [comment]
@eriknyk We ended up just [republishing separately](https://github.com/devcsrj/ts-retrofit) under:

```
 npm i axios-retrofit
```

Since my company uses this, we'll just maintain it from this fork instead

**Comment by eriknyk** [comment]
thanks @devcsrj

**Pull request closed without merging**
